[package]
name = "node02"
version = "0.1.0"
edition = "2021"

[dependencies]
async-rdma = {git = "https://github.com/datenlord/async-rdma/"}
portpicker = "0.1.1"
tokio = { version = "1", features = ["full"] }
