[package]
name = "bachelor-thesis_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
async-rdma = { git = "https://github.com/datenlord/async-rdma/", rev = "9480131f" }
tokio = { version = "1.29.1", features = ["full"] }
portpicker = "0.1.1"
